// <auto-generated />
using System;
using MemoryAlbumServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryAlbumServer.Migrations
{
    [DbContext(typeof(MemoryAlbumContext))]
    [Migration("20250222064059_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoverId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoverId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Events");

                    b.HasDiscriminator().HasValue("Event");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Media.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob");

                    b.Property<int?>("MemoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Media.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob");

                    b.Property<int?>("MemoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProfilePictureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Memory", b =>
                {
                    b.HasBaseType("MemoryAlbumServer.Models.Entities.Event");

                    b.HasDiscriminator().HasValue("Memory");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Album", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Media.Photo", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverId");

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Event", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Album", null)
                        .WithMany("Events")
                        .HasForeignKey("AlbumId");

                    b.OwnsOne("MemoryAlbumServer.Models.Entities.Position", "Location", b1 =>
                        {
                            b1.Property<int>("EventId")
                                .HasColumnType("int");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Media.Photo", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Memory", null)
                        .WithMany("Photos")
                        .HasForeignKey("MemoryId");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Media.Video", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Memory", null)
                        .WithMany("Videos")
                        .HasForeignKey("MemoryId");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Person", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Media.Photo", "ProfilePicture")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId");

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Tag", b =>
                {
                    b.HasOne("MemoryAlbumServer.Models.Entities.Event", null)
                        .WithMany("Tags")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Album", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Event", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MemoryAlbumServer.Models.Entities.Memory", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
